
# every [city] should have (either or both s3 and local paths)
# a set of global (dsm(1), dem(1), shade(3), utci(3))
# a set of local (dsm(1), dem(1), shade(3), utci(3))
# a set of masks (pedestrian(1), land_use(1)) # ⚠️ optional
# a set of 20m local (dsm(1), dem(1), shade(3), utci(3))
# a set of 20m global (dsm(1), dem(1), shade(3), utci(3))
# a set of 20m masks (pedestrian(1), land_use(1)) # ⚠️ optional

Monterrey1:
  global_dsm: https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/output_local_v4/global_building_dems/cif_dsm_ground_build.tif
  local_dsm: https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/output_local_v4/dsm_building_final_clipped.tif
  global_dem: https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/output_local_v4/global_building_dems/cif_dem.tif
  local_dem: https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/output_local_v4/dem_filled_clipped.tif
  local_dsm_path: /Users/hyejijoh/Desktop/mty/dsm_building_final_clipped.tif
  global_dsm_path: /Users/hyejijoh/Desktop/mty/cif_dsm_ground_build.tif
  local_dem_path: /Users/hyejijoh/Desktop/mty/dem_filled_clipped.tif
  global_dem_path: /Users/hyejijoh/Desktop/mty/cif_dem.tif
  shade_global:
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/scenarios/aoi/mitras_centro/baseline/Shadow_2023_172_1200D.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/scenarios/aoi/mitras_centro/baseline/Shadow_2023_172_1500D.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/scenarios/aoi/mitras_centro/baseline/Shadow_2023_172_1800D.tif
  shade_local:
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/output_local_v4/Shadow_2023_172_1200D.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/output_local_v4/Shadow_2023_172_1500D.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/output_local_v4/Shadow_2023_172_1800D.tif
  shade_local_paths:
  - /Users/hyejijoh/Desktop/mty/local/Shadow_2023_172_1200D.tif
  - /Users/hyejijoh/Desktop/mty/local/Shadow_2023_172_1500D.tif
  - /Users/hyejijoh/Desktop/mty/local/Shadow_2023_172_1800D.tif
  shade_global_paths:
  - /Users/hyejijoh/Desktop/mty/global/Shadow_2023_172_1200D.tif
  - /Users/hyejijoh/Desktop/mty/global/Shadow_2023_172_1500D.tif
  - /Users/hyejijoh/Desktop/mty/global/Shadow_2023_172_1800D.tif
  utci_global_paths:
  - /Users/hyejijoh/Desktop/mty/global/UTCI_2023_172_1200D.tif
  - /Users/hyejijoh/Desktop/mty/global/UTCI_2023_172_1500D.tif
  - /Users/hyejijoh/Desktop/mty/global/UTCI_2023_172_1800D.tif
  utci_local_paths:
  - /Users/hyejijoh/Desktop/mty/UTCI_2023_172_1200.tif
  - /Users/hyejijoh/Desktop/mty/UTCI_2023_172_1500.tif
  - /Users/hyejijoh/Desktop/mty/UTCI_2023_172_1800.tif
  mask_paths:
    pedestrian_mask: https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/scenarios/aoi/mitras_centro/baseline/pedestrian_areas.tif
    pedestrian_mask_path: /Users/hyejijoh/Desktop/mty/pedestrian_areas.tif
    land_use_mask: null
    land_use_mask_path: /Users/hyejijoh/Desktop/mty/cif_lulc_mty.tif
  shade_local_paths_20m:
  - data/resampled/Monterrey1/shade/local/Shadow_2023_172_1200D_20m.tif
  - data/resampled/Monterrey1/shade/local/Shadow_2023_172_1500D_20m.tif
  - data/resampled/Monterrey1/shade/local/Shadow_2023_172_1800D_20m.tif
  shade_global_paths_20m:
  - data/resampled/Monterrey1/shade/global/Shadow_2023_172_1200D_20m.tif
  - data/resampled/Monterrey1/shade/global/Shadow_2023_172_1500D_20m.tif
  - data/resampled/Monterrey1/shade/global/Shadow_2023_172_1800D_20m.tif
  utci_local_paths_20m:
  - data/resampled/Monterrey1/utci/local/UTCI_2023_172_1200_20m.tif
  - data/resampled/Monterrey1/utci/local/UTCI_2023_172_1500_20m.tif
  - data/resampled/Monterrey1/utci/local/UTCI_2023_172_1800_20m.tif
  utci_global_paths_20m:
  - data/resampled/Monterrey1/utci/global/UTCI_2023_172_1200D_20m.tif
  - data/resampled/Monterrey1/utci/global/UTCI_2023_172_1500D_20m.tif
  - data/resampled/Monterrey1/utci/global/UTCI_2023_172_1800D_20m.tif
  mask_paths_20m:
    pedestrian_mask_20m_path: data/resampled/Monterrey1/masks/pedestrian_mask_path_20m.tif

# ⚠️ pedestrian mask
# ⚠️ 20m resolution
Monterrey2:
  global_dsm: https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty2/global/cif_dsm_ground_build.tif
  global_dsm_path: /Users/hyejijoh/Desktop/mty2/global/cif_dsm_ground_build.tif
  local_dsm: https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty2/local/dsm_reprojected.tif
  local_dsm_path: /Users/hyejijoh/Desktop/mty2/local/dsm_reprojected.tif
  global_dem: https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty2/global/cif_dem.tif
  global_dem_path: /Users/hyejijoh/Desktop/mty2/global/cif_dem.tif
  local_dem: https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty2/local/dem_reprojected.tif
  local_dem_path: /Users/hyejijoh/Desktop/mty2/local/dem_reprojected.tif
  shade_global: 
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty2/global/Shadow_2023_172_1200D.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty2/global/Shadow_2023_172_1500D.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty2/global/Shadow_2023_172_1800D.tif
  shade_global_paths:
  - /Users/hyejijoh/Desktop/mty2/global/Shadow_2023_172_1200D.tif
  - /Users/hyejijoh/Desktop/mty2/global/Shadow_2023_172_1500D.tif
  - /Users/hyejijoh/Desktop/mty2/global/Shadow_2023_172_1800D.tif
  shade_local: 
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty2/local/Shadow_2023_172_1200D.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty2/local/Shadow_2023_172_1500D.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty2/local/Shadow_2023_172_1800D.tif
  shade_local_paths:
  - /Users/hyejijoh/Desktop/mty2/local/Shadow_2023_172_1200D.tif
  - /Users/hyejijoh/Desktop/mty2/local/Shadow_2023_172_1500D.tif
  - /Users/hyejijoh/Desktop/mty2/local/Shadow_2023_172_1800D.tif
  utci_global: 
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty2/global/UTCI_2023_172_1200.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty2/global/UTCI_2023_172_1500.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty2/global/UTCI_2023_172_1800.tif
  utci_global_paths:
  - /Users/hyejijoh/Desktop/mty2/global/UTCI_2023_172_1200.tif
  - /Users/hyejijoh/Desktop/mty2/global/UTCI_2023_172_1500.tif
  - /Users/hyejijoh/Desktop/mty2/global/UTCI_2023_172_1800.tif
  utci_local: 
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty2/local/UTCI_2023_172_1200.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty2/local/UTCI_2023_172_1500.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty2/local/UTCI_2023_172_1800.tif  
  utci_local_paths: 
  - /Users/hyejijoh/Desktop/mty2/local/UTCI_2023_172_1200.tif
  - /Users/hyejijoh/Desktop/mty2/local/UTCI_2023_172_1500.tif
  - /Users/hyejijoh/Desktop/mty2/local/UTCI_2023_172_1800.tif
  mask_paths:
    pedestrian_mask: null
    land_use_mask: https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty2/local/cif_lulc.tif


Monterrey3:
  global_dsm: null
  global_dsm_path: /Users/hyejijoh/Desktop/mty3/global/cif_dsm_ground_build.tif
  local_dsm: null
  local_dsm_path: /Users/hyejijoh/Desktop/mty3/local/dsm_reprojected.tif
  global_dem: null
  global_dem_path: /Users/hyejijoh/Desktop/mty3/global/cif_dem.tif
  local_dem: null
  local_dem_path: /Users/hyejijoh/Desktop/mty3/local/dem_reprojected.tif
  shade_global: 
  shade_global_paths:
  - /Users/hyejijoh/Desktop/mty3/global/Shadow_2023_172_1200D.tif
  - /Users/hyejijoh/Desktop/mty3/global/Shadow_2023_172_1500D.tif
  - /Users/hyejijoh/Desktop/mty3/global/Shadow_2023_172_1800D.tif
  shade_local:
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty3/local/Shadow_2023_172_1200D.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty3/local/Shadow_2023_172_1500D.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty3/local/Shadow_2023_172_1800D.tif
  shade_local_paths:
  - /Users/hyejijoh/Desktop/mty3/local/Shadow_2023_172_1200D.tif
  - /Users/hyejijoh/Desktop/mty3/local/Shadow_2023_172_1500D.tif
  - /Users/hyejijoh/Desktop/mty3/local/Shadow_2023_172_1800D.tif
  utci_global: null
  utci_global_paths:
  - /Users/hyejijoh/Desktop/mty3/global/UTCI_2023_172_1200.tif
  - /Users/hyejijoh/Desktop/mty3/global/UTCI_2023_172_1500.tif
  - /Users/hyejijoh/Desktop/mty3/global/UTCI_2023_172_1800.tif
  utci_local: 
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty3/local/UTCI_2023_172_1200.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty3/local/UTCI_2023_172_1500.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/MEX-Monterrey/mty3/local/UTCI_2023_172_1800.tif
  utci_local_paths: 
  - /Users/hyejijoh/Desktop/mty3/local/UTCI_2023_172_1200.tif
  - /Users/hyejijoh/Desktop/mty3/local/UTCI_2023_172_1500.tif
  - /Users/hyejijoh/Desktop/mty3/local/UTCI_2023_172_1800.tif
  mask_paths:
    pedestrian_mask: null
    land_use_mask: null


RiodeJaneiro:
  global_dsm_path: /Users/hyejijoh/Desktop/rdj/cif_dsm_ground_build.tif
  local_dsm_path: /Users/hyejijoh/Desktop/rdj/dsm_final_clipped.tif
  global_dem_path: /Users/hyejijoh/Desktop/rdj/cif_dem.tif
  local_dem_path: /Users/hyejijoh/Desktop/rdj/dem_final_clipped.tif
  shade_global:
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/BRA-Rio_de_janeiro/scenarios/aoi/low_emission_zone/baseline/Shadow_2022_365_1200D.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/BRA-Rio_de_janeiro/scenarios/aoi/low_emission_zone/baseline/Shadow_2022_365_1500D.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/BRA-Rio_de_janeiro/scenarios/aoi/low_emission_zone/baseline/Shadow_2022_365_1800D.tif
  shade_local:
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/BRA-Rio_de_janeiro/local_validation/Shadow_2022_365_1200D.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/BRA-Rio_de_janeiro/local_validation/Shadow_2022_365_1500D.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/BRA-Rio_de_janeiro/local_validation/Shadow_2022_365_1800D.tif
  shade_global_paths:
  - /Users/hyejijoh/Desktop/rdj/global/Shadow_2022_365_1200D.tif
  - /Users/hyejijoh/Desktop/rdj/global/Shadow_2022_365_1500D.tif
  - /Users/hyejijoh/Desktop/rdj/global/Shadow_2022_365_1800D.tif
  shade_local_paths:
  - /Users/hyejijoh/Desktop/rdj/local/Shadow_2022_365_1200D.tif
  - /Users/hyejijoh/Desktop/rdj/local/Shadow_2022_365_1500D.tif
  - /Users/hyejijoh/Desktop/rdj/local/Shadow_2022_365_1800D.tif
  utci_global:
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/BRA-Rio_de_janeiro/scenarios/aoi/low_emission_zone/baseline/UTCI_2022_365_1200D.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/BRA-Rio_de_janeiro/scenarios/aoi/low_emission_zone/baseline/UTCI_2022_365_1500D.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/BRA-Rio_de_janeiro/scenarios/aoi/low_emission_zone/baseline/UTCI_2022_365_1800D.tif
  utci_global_paths:
  - /Users/hyejijoh/Desktop/rdj/global/UTCI_2022_365_1200D.tif
  - /Users/hyejijoh/Desktop/rdj/global/UTCI_2022_365_1500D.tif
  - /Users/hyejijoh/Desktop/rdj/global/UTCI_2022_365_1800D.tif
  utci_local_paths:
  - /Users/hyejijoh/Desktop/rdj/local/UTCI_2022_365_1200.tif
  - /Users/hyejijoh/Desktop/rdj/local/UTCI_2022_365_1500.tif
  - /Users/hyejijoh/Desktop/rdj/local/UTCI_2022_365_1800.tif
  mask_paths:
    pedestrian_mask: null
    pedestrian_mask_path: /Users/hyejijoh/Desktop/rdj/pedestrian-area.tif
    land_use_mask: null
    land_use_mask_path: /Users/hyejijoh/Desktop/rdj/cif_lulc_rio.tif
  shade_local_paths_20m:
  - data/resampled/RiodeJaneiro/shade/local/Shadow_2022_365_1200D_20m.tif
  - data/resampled/RiodeJaneiro/shade/local/Shadow_2022_365_1500D_20m.tif
  - data/resampled/RiodeJaneiro/shade/local/Shadow_2022_365_1800D_20m.tif
  shade_global_paths_20m:
  - data/resampled/RiodeJaneiro/shade/global/Shadow_2022_365_1200D_20m.tif
  - data/resampled/RiodeJaneiro/shade/global/Shadow_2022_365_1500D_20m.tif
  - data/resampled/RiodeJaneiro/shade/global/Shadow_2022_365_1800D_20m.tif
  utci_local_paths_20m:
  - data/resampled/RiodeJaneiro/utci/local/UTCI_2022_365_1200_20m.tif
  - data/resampled/RiodeJaneiro/utci/local/UTCI_2022_365_1500_20m.tif
  - data/resampled/RiodeJaneiro/utci/local/UTCI_2022_365_1800_20m.tif
  utci_global_paths_20m:
  - data/resampled/RiodeJaneiro/utci/global/UTCI_2022_365_1200D_20m.tif
  - data/resampled/RiodeJaneiro/utci/global/UTCI_2022_365_1500D_20m.tif
  - data/resampled/RiodeJaneiro/utci/global/UTCI_2022_365_1800D_20m.tif
  mask_paths_20m:
    pedestrian_mask_path: null
    land_use_mask_path: null

# ‼️ needs global data
CapeTown:
  global_dsm: https://wri-cities-heat.s3.us-east-1.amazonaws.com/ZAF-Cape_Town/validation/global/cif_dsm_ground_build.tif
  local_dsm: null
  global_dem: https://wri-cities-heat.s3.us-east-1.amazonaws.com/ZAF-Cape_Town/validation/global/cif_dem.tif
  local_dem: null
  shade_global: 
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/ZAF-Cape_Town/validation/global/Shadow_2023_1_1200D.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/ZAF-Cape_Town/validation/global/Shadow_2023_172_1500D.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/ZAF-Cape_Town/validation/global/Shadow_2023_172_1800D.tif
  shade_global_paths:
  - /Users/hyejijoh/Desktop/capetown/global/Shadow_2023_1_1200D.tif
  - /Users/hyejijoh/Desktop/capetown/global/Shadow_2023_172_1500D.tif
  - /Users/hyejijoh/Desktop/capetown/global/Shadow_2023_172_1800D.tif
  shade_local: null
  utci_global: 
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/ZAF-Cape_Town/validation/global/UTCI_2023_1_1200.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/ZAF-Cape_Town/validation/global/UTCI_2023_172_1500.tif
  - https://wri-cities-heat.s3.us-east-1.amazonaws.com/ZAF-Cape_Town/validation/global/UTCI_2023_172_1800.tif
  utci_global_paths:
  - /Users/hyejijoh/Desktop/capetown/global/UTCI_2023_1_1200.tif
  - /Users/hyejijoh/Desktop/capetown/global/UTCI_2023_172_1500.tif
  - /Users/hyejijoh/Desktop/capetown/global/UTCI_2023_172_1800.tif
  utci_local: null
  pedestrian_mask: null

Amsterdam:
  global_dsm: null
  global_dsm_path: /Users/hyejijoh/Desktop/amsterdam/global/cif_dsm_ground_build.tif
  local_dsm: null
  local_dsm_path: /Users/hyejijoh/Desktop/amsterdam/local/aoi2_building_final.tif
  global_dem: null
  global_dem_path: /Users/hyejijoh/Desktop/amsterdam/global/cif_dem.tif
  local_dem: null
  local_dem_path: /Users/hyejijoh/Desktop/amsterdam/local/aoi2_dem_final.tif
  shade_global: null
  shade_global_paths: 
  - /Users/hyejijoh/Desktop/amsterdam/global/Shadow_2023_189_1200D.tif
  - /Users/hyejijoh/Desktop/amsterdam/global/Shadow_2023_189_1500D.tif
  - /Users/hyejijoh/Desktop/amsterdam/global/Shadow_2023_189_1800D.tif
  shade_local: null
  shade_local_paths: 
  - /Users/hyejijoh/Desktop/amsterdam/local/Shadow_2023_189_1200D.tif
  - /Users/hyejijoh/Desktop/amsterdam/local/Shadow_2023_189_1500D.tif
  - /Users/hyejijoh/Desktop/amsterdam/local/Shadow_2023_189_1800D.tif
  utci_global: null
  utci_global_paths:
  - /Users/hyejijoh/Desktop/amsterdam/global/UTCI_2023_189_1200.tif
  - /Users/hyejijoh/Desktop/amsterdam/global/UTCI_2023_189_1500.tif
  - /Users/hyejijoh/Desktop/amsterdam/global/UTCI_2023_189_1800.tif
  utci_local: null
  utci_local_paths:
  - /Users/hyejijoh/Desktop/amsterdam/local/UTCI_2023_189_1200.tif
  - /Users/hyejijoh/Desktop/amsterdam/local/UTCI_2023_189_1500.tif
  - /Users/hyejijoh/Desktop/amsterdam/local/UTCI_2023_189_1800.tif
  pedestrian_mask: null